<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\SanPham;
use App\Models\LoaiSanPham;

class VenusProductSeeder extends Seeder
{
    public function run()
    {
        // Tạo categories trước
        $categories = [
            ['ten_loai' => 'Cleanser', 'mota' => 'Gentle cleansing products for all skin types'],
            ['ten_loai' => 'Serum', 'mota' => 'High-active treatment serums'],
            ['ten_loai' => 'Moisturizer', 'mota' => 'Hydrating and nourishing creams'],
            ['ten_loai' => 'Sunscreen', 'mota' => 'UV protection products'],
            ['ten_loai' => 'Foundation', 'mota' => 'Base makeup for flawless coverage'],
            ['ten_loai' => 'Lipstick', 'mota' => 'Vibrant and long-lasting lip colors'],
            ['ten_loai' => 'Eyeshadow', 'mota' => 'Eye makeup for stunning looks'],
            ['ten_loai' => 'Mascara', 'mota' => 'Enhance your lashes'],
            ['ten_loai' => 'Toner', 'mota' => 'Balancing and refreshing toners'],
            ['ten_loai' => 'Eye Cream', 'mota' => 'Specialized care for delicate eye area'],
        ];

        foreach ($categories as $category) {
            LoaiSanPham::firstOrCreate(['ten_loai' => $category['ten_loai']], $category);
        }

        // Lấy ID của categories
        $cleanser = LoaiSanPham::where('ten_loai', 'Cleanser')->first()->id_loai;
        $serum = LoaiSanPham::where('ten_loai', 'Serum')->first()->id_loai;
        $moisturizer = LoaiSanPham::where('ten_loai', 'Moisturizer')->first()->id_loai;
        $sunscreen = LoaiSanPham::where('ten_loai', 'Sunscreen')->first()->id_loai;
        $foundation = LoaiSanPham::where('ten_loai', 'Foundation')->first()->id_loai;
        $lipstick = LoaiSanPham::where('ten_loai', 'Lipstick')->first()->id_loai;
        $eyeshadow = LoaiSanPham::where('ten_loai', 'Eyeshadow')->first()->id_loai;
        $mascara = LoaiSanPham::where('ten_loai', 'Mascara')->first()->id_loai;
        $toner = LoaiSanPham::where('ten_loai', 'Toner')->first()->id_loai;
        $eyecream = LoaiSanPham::where('ten_loai', 'Eye Cream')->first()->id_loai;

        // 20 sản phẩm từ các thương hiệu nổi tiếng (10 dưỡng da + 10 makeup)
        $products = [
            // === DƯỠNG DA (10 sản phẩm) ===
            [
                'ten_sanpham' => 'La Mer The Moisturizing Cream',
                'mota' => 'Iconic luxury moisturizer with Miracle Broth™. Transforms skin with extraordinary healing and renewal properties for softer, smoother complexion.',
                'gia' => 6800000,
                'so_luong' => 25,
                'dungtich' => '60ml',
                'id_loai' => $moisturizer,
                'thuonghieu' => 'La Mer',
                'xuatxu' => 'USA',
                'thanhphan' => 'Miracle Broth, Sea Kelp Ferment, Calcium, Magnesium, Potassium',
                'huongdan' => 'Warm between fingertips and press gently into skin. Use morning and evening.',
                'hinh_anh' => 'la-mer-moisturizing-cream.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'SK-II Facial Treatment Essence',
                'mota' => 'Legendary essence containing 90% PITERA™. Improves skin texture, clarity and radiance for crystal clear skin.',
                'gia' => 4200000,
                'so_luong' => 40,
                'dungtich' => '160ml',
                'id_loai' => $toner,
                'thuonghieu' => 'SK-II',
                'xuatxu' => 'Japan',
                'thanhphan' => '90% PITERA, Galactomyces Ferment Filtrate, Niacinamide',
                'huongdan' => 'Apply with cotton pad or hands after cleansing. Pat gently into skin.',
                'hinh_anh' => 'sk2-facial-essence.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Estée Lauder Advanced Night Repair Serum',
                'mota' => 'Revolutionary anti-aging serum with ChronoluxCB™ technology. Repairs signs of aging while you sleep for younger-looking skin.',
                'gia' => 3500000,
                'so_luong' => 35,
                'dungtich' => '50ml',
                'id_loai' => $serum,
                'thuonghieu' => 'Estée Lauder',
                'xuatxu' => 'USA',
                'thanhphan' => 'ChronoluxCB Technology, Tripeptide-32, Bifida Ferment Lysate',
                'huongdan' => 'Apply to clean skin every evening before moisturizer.',
                'hinh_anh' => 'estee-lauder-night-repair.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Clinique Dramatically Different Moisturizing Lotion+',
                'mota' => 'Dermatologist-developed moisturizer that strengthens skin barrier. Provides all-day hydration for softer, smoother skin.',
                'gia' => 1800000,
                'so_luong' => 50,
                'dungtich' => '125ml',
                'id_loai' => $moisturizer,
                'thuonghieu' => 'Clinique',
                'xuatxu' => 'USA',
                'thanhphan' => 'Hyaluronic Acid, Glycerin, Barley Extract, Cucumber Fruit Extract',
                'huongdan' => 'Apply twice daily to face and neck after cleansing.',
                'hinh_anh' => 'clinique-moisturizing-lotion.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Drunk Elephant C-Firma Day Serum',
                'mota' => 'Potent vitamin C serum with 15% L-Ascorbic Acid. Brightens, firms and improves signs of photodamage for radiant skin.',
                'gia' => 2200000,
                'so_luong' => 30,
                'dungtich' => '30ml',
                'id_loai' => $serum,
                'thuonghieu' => 'Drunk Elephant',
                'xuatxu' => 'USA',
                'thanhphan' => '15% L-Ascorbic Acid, Ferulic Acid, Vitamin E, Pumpkin Ferment Extract',
                'huongdan' => 'Apply to clean dry skin in the morning. Follow with moisturizer and SPF.',
                'hinh_anh' => 'drunk-elephant-c-firma.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Lancôme Rénergie H.C.F. Triple Serum',
                'mota' => 'Triple-action anti-aging serum with Hyaluronic Acid, Vitamin C+Niacinamide, and Ferulic Acid. Visibly reduces signs of aging.',
                'gia' => 4800000,
                'so_luong' => 28,
                'dungtich' => '50ml',
                'id_loai' => $serum,
                'thuonghieu' => 'Lancôme',
                'xuatxu' => 'France',
                'thanhphan' => 'Hyaluronic Acid, Vitamin C, Niacinamide, Ferulic Acid',
                'huongdan' => 'Apply morning and evening to face and neck before moisturizer.',
                'hinh_anh' => 'lancome-triple-serum.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Kiehl\'s Ultra Facial Cleanser',
                'mota' => 'Gentle daily cleanser for all skin types. Effectively removes dirt and excess oil without stripping skin\'s natural moisture.',
                'gia' => 1200000,
                'so_luong' => 60,
                'dungtich' => '150ml',
                'id_loai' => $cleanser,
                'thuonghieu' => 'Kiehl\'s',
                'xuatxu' => 'USA',
                'thanhphan' => 'Squalane, Glycerin, Cucumber Fruit Extract, Vitamin E',
                'huongdan' => 'Massage onto damp skin, then rinse thoroughly with water. Use twice daily.',
                'hinh_anh' => 'kiehls-ultra-facial-cleanser.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Shiseido Ultimune Power Infusing Concentrate',
                'mota' => 'Revolutionary serum that strengthens skin\'s natural defenses. Contains ImuGeneration Technology for resilient, youthful skin.',
                'gia' => 3800000,
                'so_luong' => 32,
                'dungtich' => '75ml',
                'id_loai' => $serum,
                'thuonghieu' => 'Shiseido',
                'xuatxu' => 'Japan',
                'thanhphan' => 'ImuGeneration Technology, Reishi Mushroom, Iris Root Extract',
                'huongdan' => 'Apply to clean skin morning and evening before moisturizer.',
                'hinh_anh' => 'shiseido-ultimune.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'The Ordinary Niacinamide 10% + Zinc 1%',
                'mota' => 'High-strength serum to reduce appearance of skin blemishes and congestion. Balances visible aspects of sebum activity.',
                'gia' => 350000,
                'so_luong' => 80,
                'dungtich' => '30ml',
                'id_loai' => $serum,
                'thuonghieu' => 'The Ordinary',
                'xuatxu' => 'Canada',
                'thanhphan' => '10% Niacinamide, 1% Zinc PCA, Hyaluronic Acid',
                'huongdan' => 'Apply to entire face morning and evening after cleansing.',
                'hinh_anh' => 'the-ordinary-niacinamide.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'La Roche-Posay Anthelios Ultra Light Sunscreen SPF50+',
                'mota' => 'Broad-spectrum sunscreen with Cell-Ox Shield antioxidant complex. Lightweight, non-greasy formula for daily protection.',
                'gia' => 680000,
                'so_luong' => 70,
                'dungtich' => '60ml',
                'id_loai' => $sunscreen,
                'thuonghieu' => 'La Roche-Posay',
                'xuatxu' => 'France',
                'thanhphan' => 'Avobenzone, Homosalate, Octisalate, Octocrylene, Cell-Ox Shield',
                'huongdan' => 'Apply generously 15 minutes before sun exposure. Reapply every 2 hours.',
                'hinh_anh' => 'laroche-posay-sunscreen.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // === MAKEUP (10 sản phẩm) ===
            [
                'ten_sanpham' => 'Dior Forever Foundation - 2N Neutral',
                'mota' => 'Full coverage foundation with 24h wear. Clean formula with 86% skincare base for flawless, natural-looking finish.',
                'gia' => 2200000,
                'so_luong' => 45,
                'dungtich' => '30ml',
                'id_loai' => $foundation,
                'thuonghieu' => 'Dior',
                'xuatxu' => 'France',
                'thanhphan' => '86% Skincare Base, SPF35, Hyaluronic Acid, Wild Pansy Extract',
                'huongdan' => 'Apply with brush or beauty sponge from center outward.',
                'hinh_anh' => 'dior-forever-foundation.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Chanel Rouge Allure Lipstick - 99 Pirate',
                'mota' => 'Iconic lipstick with intense color and luminous finish. Long-wearing formula with comfortable texture.',
                'gia' => 1800000,
                'so_luong' => 55,
                'dungtich' => '3.5g',
                'id_loai' => $lipstick,
                'thuonghieu' => 'Chanel',
                'xuatxu' => 'France',
                'thanhphan' => 'Vitamin E, Mimosa, Jojoba Oil, Rose Wax',
                'huongdan' => 'Apply directly from bullet or use lip brush for precision.',
                'hinh_anh' => 'chanel-rouge-allure.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Urban Decay Naked3 Eyeshadow Palette',
                'mota' => '12 rose-hued neutral eyeshadows in matte and shimmer finishes. Buttery smooth texture with high color payoff.',
                'gia' => 2500000,
                'so_luong' => 30,
                'dungtich' => '15.6g',
                'id_loai' => $eyeshadow,
                'thuonghieu' => 'Urban Decay',
                'xuatxu' => 'USA',
                'thanhphan' => 'Mica, Talc, Dimethicone, Vitamin E',
                'huongdan' => 'Use brushes to apply and blend. Build intensity with layers.',
                'hinh_anh' => 'urban-decay-naked3.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Benefit Cosmetics BADgal BANG! Mascara',
                'mota' => 'Volumizing mascara with gravity-defying formula. Creates dramatic volume and length for bold, beautiful lashes.',
                'gia' => 1200000,
                'so_luong' => 60,
                'dungtich' => '8.5g',
                'id_loai' => $mascara,
                'thuonghieu' => 'Benefit',
                'xuatxu' => 'USA',
                'thanhphan' => 'Aero-particles, ProVitamin B5, Volumizing Fibers',
                'huongdan' => 'Apply from root to tip in zigzag motion. Layer for more drama.',
                'hinh_anh' => 'benefit-badgal-bang.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'MAC Studio Fix Foundation - NC25',
                'mota' => 'Medium-to-full coverage foundation and powder in one. Oil-free formula provides natural matte finish.',
                'gia' => 1650000,
                'so_luong' => 40,
                'dungtich' => '15g',
                'id_loai' => $foundation,
                'thuonghieu' => 'MAC',
                'xuatxu' => 'Canada',
                'thanhphan' => 'Oil-absorbing powder, SPF15, Vitamin E',
                'huongdan' => 'Apply with damp sponge for medium coverage or dry for full coverage.',
                'hinh_anh' => 'mac-studio-fix.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'YSL Rouge Pur Couture Lipstick - 01 Le Rouge',
                'mota' => 'Luxurious lipstick with intense color and creamy texture. Long-wearing formula with elegant gold packaging.',
                'gia' => 1950000,
                'so_luong' => 50,
                'dungtich' => '3.8g',
                'id_loai' => $lipstick,
                'thuonghieu' => 'YSL',
                'xuatxu' => 'France',
                'thanhphan' => 'Hyaluronic Acid Spheres, Maracuja Oil, Mango Butter',
                'huongdan' => 'Apply from center of lips outward. Blot and reapply for intensity.',
                'hinh_anh' => 'ysl-rouge-pur-couture.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Charlotte Tilbury Pillow Talk Eyeshadow Palette',
                'mota' => '12-pan eyeshadow palette in universally flattering rose-gold tones. Mix of matte, shimmer, and metallic finishes.',
                'gia' => 2800000,
                'so_luong' => 25,
                'dungtich' => '16g',
                'id_loai' => $eyeshadow,
                'thuonghieu' => 'Charlotte Tilbury',
                'xuatxu' => 'UK',
                'thanhphan' => 'Mica, Synthetic Fluorphlogopite, Dimethicone',
                'huongdan' => 'Use flat brush for shimmer, fluffy for blending. Follow the eye map guide.',
                'hinh_anh' => 'charlotte-tilbury-pillow-talk.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Too Faced Better Than Sex Mascara',
                'mota' => 'Volumizing mascara with hourglass-shaped brush. Creates dramatic volume and curl for sexy, bold lashes.',
                'gia' => 1100000,
                'so_luong' => 65,
                'dungtich' => '8ml',
                'id_loai' => $mascara,
                'thuonghieu' => 'Too Faced',
                'xuatxu' => 'USA',
                'thanhphan' => 'Collagen, Peptides, Panthenol, Olivem',
                'huongdan' => 'Wiggle brush at base of lashes, then sweep upward to tips.',
                'hinh_anh' => 'too-faced-better-than-sex.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'NARS Orgasm Blush',
                'mota' => 'Iconic peachy-pink blush with golden undertones. Buildable color with silky smooth texture for natural flush.',
                'gia' => 1450000,
                'so_luong' => 55,
                'dungtich' => '4.8g',
                'id_loai' => $eyeshadow, // Using eyeshadow category for blush
                'thuonghieu' => 'NARS',
                'xuatxu' => 'France',
                'thanhphan' => 'Mica, Talc, Dimethicone, Vitamin E',
                'huongdan' => 'Apply to apples of cheeks and blend upward toward temples.',
                'hinh_anh' => 'nars-orgasm-blush.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Fenty Beauty Gloss Bomb - Fenty Glow',
                'mota' => 'Universal lip luminizer with explosive shine. Non-sticky formula with peach-vanilla scent for fuller-looking lips.',
                'gia' => 950000,
                'so_luong' => 70,
                'dungtich' => '9ml',
                'id_loai' => $lipstick,
                'thuonghieu' => 'Fenty Beauty',
                'xuatxu' => 'USA',
                'thanhphan' => 'Shea Butter, Vitamin E, Vanilla Extract',
                'huongdan' => 'Apply alone or over lipstick for extra shine and dimension.',
                'hinh_anh' => 'fenty-gloss-bomb.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert products
        foreach ($products as $product) {
            SanPham::firstOrCreate(
                ['ten_sanpham' => $product['ten_sanpham']],
                $product
            );
        }
    }
}
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Pure Cleansing Balm',
                'mota' => 'Gentle yet effective cleansing balm that melts away makeup and impurities. Infused with nourishing oils to leave skin soft, clean, and perfectly balanced.',
                'gia' => 750000,
                'so_luong' => 60,
                'loai_id' => 1, // Cleanser
                'thuonghieu' => 'Venus',
                'xuatxu' => 'France',
                'thanhphan' => 'Jojoba Oil, Chamomile Extract, Green Tea, Vitamin E',
                'huongdan' => 'Massage onto dry skin, add water to emulsify, then rinse thoroughly.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Defense SPF 50',
                'mota' => 'Invisible, weightless sunscreen with broad-spectrum protection. Advanced formula protects against UVA/UVB rays while providing antioxidant benefits for healthy-looking skin.',
                'gia' => 650000,
                'so_luong' => 45,
                'loai_id' => 4, // Sunscreen
                'thuonghieu' => 'Venus',
                'xuatxu' => 'Japan',
                'thanhphan' => 'Zinc Oxide, Titanium Dioxide, Niacinamide, Antioxidant Complex',
                'huongdan' => 'Apply generously to face and neck 15 minutes before sun exposure. Reapply every 2 hours.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Age-Reverse Night Treatment',
                'mota' => 'Intensive overnight treatment with retinol and peptides. Works while you sleep to visibly reduce signs of aging, improve skin texture, and restore youthful radiance.',
                'gia' => 1450000,
                'so_luong' => 25,
                'loai_id' => 2, // Serum
                'thuonghieu' => 'Venus',
                'xuatxu' => 'USA',
                'thanhphan' => '0.5% Retinol, Peptide Complex, Bakuchiol, Squalane',
                'huongdan' => 'Apply to clean skin at night. Start 2x per week, gradually increase frequency.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Brightening Eye Complex',
                'mota' => 'Targeted eye treatment that reduces dark circles, puffiness, and fine lines. Caffeine and peptides work together to refresh and rejuvenate the delicate eye area.',
                'gia' => 850000,
                'so_luong' => 40,
                'loai_id' => 2, // Serum
                'thuonghieu' => 'Venus',
                'xuatxu' => 'South Korea',
                'thanhphan' => 'Caffeine, Peptides, Vitamin K, Hyaluronic Acid',
                'huongdan' => 'Gently pat around eye area morning and evening.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Gentle Exfoliating Toner',
                'mota' => 'Daily use toner with AHA/BHA blend that gently exfoliates and refines pores. Reveals smoother, brighter skin while maintaining optimal moisture balance.',
                'gia' => 550000,
                'so_luong' => 55,
                'loai_id' => 1, // Cleanser category
                'thuonghieu' => 'Venus',
                'xuatxu' => 'France',
                'thanhphan' => 'Glycolic Acid, Lactic Acid, Salicylic Acid, Rose Water',
                'huongdan' => 'Apply with cotton pad or gentle patting motions after cleansing.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Daily Gentle Cleanser',
                'mota' => 'Gentle foaming cleanser for daily use. Removes makeup and impurities without stripping natural oils, suitable for all skin types.',
                'gia' => 280000,
                'so_luong' => 60,
                'dungtich' => '150ml',
                'id_loai' => $cleanser,
                'thuonghieu' => 'Venus',
                'xuatxu' => 'France',
                'thanhphan' => 'Mild Surfactants, Chamomile Extract, Glycerin, Panthenol',
                'huongdan' => 'Apply to wet face, massage gently, rinse with warm water.',
                'hinh_anh' => 'venus-gentle-cleanser.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Hydrating Toner',
                'mota' => 'Alcohol-free toner that balances and refreshes skin. Contains natural botanicals to prepare skin for better product absorption.',
                'gia' => 320000,
                'so_luong' => 45,
                'dungtich' => '200ml',
                'id_loai' => $toner,
                'thuonghieu' => 'Venus',
                'xuatxu' => 'France',
                'thanhphan' => 'Rose Water, Hyaluronic Acid, Green Tea Extract, Aloe Vera',
                'huongdan' => 'Apply with cotton pad or pat gently into skin after cleansing.',
                'hinh_anh' => 'venus-hydrating-toner.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Vitamin C Daily Serum',
                'mota' => 'Brightening serum with stable vitamin C derivative. Helps reduce dark spots and improves skin radiance with continued use.',
                'gia' => 450000,
                'so_luong' => 35,
                'dungtich' => '30ml',
                'id_loai' => $serum,
                'thuonghieu' => 'Venus',
                'xuatxu' => 'France',
                'thanhphan' => 'Magnesium Ascorbyl Phosphate, Niacinamide, Hyaluronic Acid, Ferulic Acid',
                'huongdan' => 'Apply 2-3 drops to clean skin in the morning before moisturizer.',
                'hinh_anh' => 'venus-vitamin-c-serum.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Daily Moisturizer SPF30',
                'mota' => 'Lightweight moisturizer with broad-spectrum sun protection. Perfect for daily use, provides hydration and UV protection in one step.',
                'gia' => 380000,
                'so_luong' => 50,
                'dungtich' => '50ml',
                'id_loai' => $sunscreen,
                'thuonghieu' => 'Venus',
                'xuatxu' => 'France',
                'thanhphan' => 'Zinc Oxide, Titanium Dioxide, Hyaluronic Acid, Ceramides',
                'huongdan' => 'Apply generously to face and neck every morning as final step.',
                'hinh_anh' => 'venus-daily-moisturizer-spf.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ten_sanpham' => 'Venus Restorative Face Mask',
                'mota' => 'Weekly treatment mask with marine collagen and botanical extracts. Intensively hydrates and firms skin, leaving it visibly plumper and more youthful.',
                'gia' => 1150000,
                'so_luong' => 30,
                'dungtich' => '50ml',
                'id_loai' => $moisturizer,
                'thuonghieu' => 'Venus',
                'xuatxu' => 'France',
                'thanhphan' => 'Marine Collagen, Hyaluronic Acid, Botanical Extracts, Algae',
                'huongdan' => 'Apply thick layer to clean skin for 15-20 minutes. Remove with warm water.',
                'hinh_anh' => 'venus-face-mask.jpg',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($products as $product) {
            SanPham::create($product);
        }
    }
}
